# Generated by Django 3.2.25 on 2025-06-10 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_rename_hora_creacion_publicacion_fecha_publicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulauno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=200)),
                ('equipo', models.CharField(max_length=200)),
                ('nacimiento', models.IntegerField()),
                ('carreras_ganadas', models.IntegerField()),
                ('campeonatos_corridos', models.IntegerField()),
                ('biografia', models.TextField()),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
